[project]
name = "plintools"
version = "0.1.0"
description = "Decode LIN frames on peak lin"
authors = [{ name = "Daniel Trnka", email = "daniel.trnka@gmail.com" }]
requires-python = ">=3.8.1,<4"
readme = "README.md"
dependencies = [
    "ldfparser>=0.25.0,<0.26",
    "plin-linux>=0.0.3,<0.0.4",
    "textual>=0.78.0,<0.79",
]

[project.scripts]
plintools = "plintools.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
